var langs = {
	en: {
		step1Title: "WARNING!",
		step2Title: "Question 1",
		step3Title: "Question 2",
		step4Title: "Question 3",
		step5Title: "Thank you!",
		step1Paragraph: "You will see nude photos. Please be discreet.",
		step2Paragraph: "Many of these women are desperate single moms and cheating wives looking for some fun. They could be your neighbors or someone you know. Do you agree to keep the identity of these women a secret?",
		step3Paragraph: "These women have asked us to not allow men that are seeking a \"relationship\". They only desire quick sex. Not dating. Do you agree to this request?",
		step4Paragraph: "Are you at least 25 years old? The women have requested that we not let those younger than 25 contact them because of past rude behavior by younger men.",
		step5Paragraph: "You may now see our list and photos of women who are in your area. Again, please keep their identity a secret. Click on the \"Continue\" button and search on the basis of your answers.",
		btnContinue: "Continue",
		btnYes: "yes",
		btnNo: "no",
		btnNext: "Next",
		btnBack: "Back",
        adult: "adult only",
        chatTitle: 'Activity in your area',
        msgPhrase1: 'post nude photo',
        msgPhrase2: 'have a great sex',
        msgPhrase3: 'is looking for sex',
        msgPhrase4: 'invite you on nude party',
	},
	ar: {
		step1Title: "تحذير!",
		step2Title: "1 السؤال رقم",
		step3Title: "2 السؤال رقم",
		step4Title: "3 السؤال رقم",
		step5Title: "شكراً لك!",
		step1Paragraph: "سترى صوراً عارية. يرجى توخي الحذر.",
		step2Paragraph: "العديد من هؤلاء النساء هن أمهات عازبات يائسات وزوجات خائنات يبحثن عن بعض المرح. يمكن أن يكونوا جيرانك أو أي شخص تعرفه. هل توافق على الحفاظ على سرية هوية هؤلاء النساء؟",
		step3Paragraph: "لقد طلبت منا هؤلاء النساء ألا نسمح للرجال الذين يسعون إلى \"علاقة عاطفية\". حيث أنهن يرغبن في ممارسة الجنس السريع، بدون مواعدة. هل توافق على هذا الطلب؟",
		step4Paragraph: "هل عمرك 25 عاماً على الأقل؟ لقد طلبت النساء ألا نسمح لأولئك الذين تقل أعمارهم عن 25 عامًا بالاتصال بهم بسبب بعض التصرفات الفظة من قبل الشباب الأصغر سناً.",
		step5Paragraph: "يمكنك الآن مشاهدة قائمتنا وصور النساء الموجودات في منطقتك. مرة أخرى، يرجى الحفاظ على سرية هويتهم. انقر زر \"استمر\" وابحث بناءً على إجاباتك.",
		btnContinue: "استمر",
		btnYes: "لا",
		btnNo: " نعم",
		btnNext: "استمر",
		btnBack: " التالي",
        adult: "للبالغين فقط",
        chatTitle: 'النشاط في منطقتك',
        msgPhrase1: 'آخر صورة عارية',
        msgPhrase2: 'ممارسة الجنس بشكل رائع',
        msgPhrase3: 'تبحث عن الجنس',
        msgPhrase4: 'ندعوك في حفلة عارية',
	},
	az: {
		step1Title: "DİQQƏT!",
		step2Title: "sual 1",
		step3Title: "sual 2",
		step4Title: "sual 3",
		step5Title: "Çox sağ ol!",
		step1Paragraph: "Çılpaq fotoları görəcəksiniz. Xahiş edirəm təmkinli olun.",
		step2Paragraph: "Bu qadınların çoxu ümidsiz tək moms və əyləncəli arvad axtaran qadınlardır. Onlar sizin qonşularınız və ya tanıdığınız biri ola bilər. Bu qadınların kimliyini gizli saxlamağa razısınız?",
		step3Paragraph: 'Bu qadınlar "əlaqələr" axtaran kişilərə icazə verməməyimizi istədi. Yalnız tez cinsi əlaqə arzulayırlar. Tanış deyiləm. Bu tələblə razısınız?',
		step4Paragraph: "Ən azı 25 yaşın var? Qadınlar, 25 yaşdan kiçik olanların, gənc kişilərin keçmiş kobud davranışlarına görə onlarla əlaqə yaratmamağımızı istədi.",
		step5Paragraph: 'İndi siyahımızı və ərazinizdə olan qadınların fotolarını görə bilərsiniz. Yenə də şəxsiyyətlərini gizli saxla "Davam et" düyməsini vurun və cavablarınız əsasında axtarış aparın.',
		btnContinue: "Davam edin",
		btnYes: "Bəli",
		btnNo: "YOX",
		btnNext: "Davam edin",
		btnBack: "Geri",
        adult: "yalnız böyüklər",
        chatTitle: 'Bölgənizdəki fəaliyyət',
        msgPhrase1: 'çılpaq foto göndər',
        msgPhrase2: 'böyük cinsi əlaqə',
        msgPhrase3: 'seks axtarir',
        msgPhrase4: 'çılpaq tərəfə dəvət edirəm',
	},
	tr: {
		step1Title: "UYARI!",
		step2Title: "soru 1",
		step3Title: "soru 2",
		step4Title: "soru 3",
		step5Title: "Teşekkür ederim!",
		step1Paragraph: "Çıplak fotoğraflar göreceksiniz. Lütfen sağduyulu olun.",
		step2Paragraph: "Bu kadınların çoğu umutsuz bekar anneler ve biraz eğlence arayan hile eşler. Komşularınız veya tanıdığınız biri olabilirler. Bu kadınların kimliğini gizli tutmayı kabul ediyor musunuz?",
		step3Paragraph: 'Bu kadınlar bizden "ilişki" arayan erkeklere izin vermemizi istedi. Sadece hızlı seks istiyorlar. Arkadaş değil. Bu talebi kabul ediyor musunuz?',
		step4Paragraph: "En az 25 yaşında mısın? Kadınlar, 25 yaşından küçüklerin, daha genç erkeklerin geçmiş kaba davranışları nedeniyle onlarla iletişim kurmasını istemedik.",
		step5Paragraph: 'Artık listemiz ve bölgenizdeki kadınların fotoğraflarını görebilirsiniz. Yine, lütfen kimliklerini bir sır olarak saklayın. "Devam" düğmesini tıklayın ve yanıtlarınıza göre arama yapın.',
		btnContinue: "Devam et",
		btnYes: "EVET",
		btnNo: "HAYIR",
		btnNext: "Devam et",
		btnBack: "Geri",
        adult: "sadece yetişkinlere özel",
        chatTitle: 'Bölgenizdeki etkinlik',
        msgPhrase1: 'çıplak fotoğraf sonrası',
        msgPhrase2: 'iyi seks',
        msgPhrase3: 'seks arıyor',
        msgPhrase4: 'seni çıplak partiye davet et',
	},
	uk: {
		step1Title: "Увага!",
		step2Title: "Питання 1",
		step3Title: "Питання 2",
		step4Title: "Питання 3",
		step5Title: "Дякую!",
		step1Paragraph: "Ви побачите оголені фотографії. Будьте уважні.",
		step2Paragraph: "Багато з цих жінок - відчайдушні одинокі мами та обманюючі дружини, які шукають задоволення. Вони можуть бути вашими сусідами чи кимсь, кого ви знаєте. Чи погоджуєтесь ви зберігати особу цих жінок в таємниці?",
		step3Paragraph: 'Ці жінки попросили нас не допускати чоловіків, які шукають "стосунків". Вони бажають лише швидкого сексу. Не знайомства. Чи згодні ви з цим запитом?',
		step4Paragraph: "Вам щонайменше 25 років? Жінки просили, щоб ми не дозволяли контактувати з ними молодшим за 25 років через грубу поведінку молодих чоловіків.",
		step5Paragraph: "Тепер ви можете побачити наш список та фотографії жінок, які перебувають у вашому районі. Знову будь ласка, зберігайте їхню особу в таємниці. Клацніть на \"Продовжити\" кнопка та пошук на основі ваших відповідей.",
		btnContinue: "Продовжии",
		btnYes: "так",
		btnNo: "ні",
		btnNext: "Далі",
		btnBack: "Назад",
        adult: "лише для дорослих",
        chatTitle: 'Активність у вашому районі',
        msgPhrase1: 'завантажте фотографії еротичного характеру',
        msgPhrase2: 'мати хороший секс',
        msgPhrase3: 'бажає сексу',
        msgPhrase4: 'запрошує тебе на оголену вечірку',
	},
	ru: {
		step1Title: "Внимание!",
		step2Title: "Вопрос 1",
		step3Title: "Вопрос 2",
		step4Title: "Вопрос 3",
		step5Title: "Спасибо!",
		step1Paragraph: "Вы увидите обнаженные фотографии. Пожалуйста, будьте осмотрительны.",
		step2Paragraph: "Многие из этих женщин - отчаянные одинокие мамы и обманывающие жены, ищущие веселья. Они могут быть вашими соседями или знакомыми. Согласны ли вы сохранить личность этих женщин в секрете?",
		step3Paragraph: 'Эти женщины просили нас не пропускать мужчин, которые ищут "отношения". Они только хотят быстрого секса. Без свиданий. Вы согласны с этим запросом?',
		step4Paragraph: "Вам уже исполнилось 25 лет? Женщины просили, чтобы мы не позволяли лицам моложе 25 лет, выходить на контакт с ними из-за предшествующего грубого поведения молодых парней.",
		step5Paragraph: "Теперь вы можете увидеть список и фотографии женщин, которые находятся в вашем районе. Будьте добры, держите их личность в секрете. Нажмите кнопку «Продолжить» и осуществляйте поиск на основе ваших ответов.",
		btnContinue: "Продолжить",
		btnYes: "ДА",
		btnNo: "НЕТ",
		btnNext: "Далее",
		btnBack: "Назад",
        adult: "только для взрослых",
        chatTitle: 'Активность в вашем районе',
        msgPhrase1: 'загрузите фотографии эротического характера',
        msgPhrase2: 'иметь хороший секс',
        msgPhrase3: 'желает секса',
        msgPhrase4: 'приглашает тебя на обнажённую вечеринку',
	},
	ro: {
		step1Title: "AVERTIZARE!",
		step2Title: "intrebarea 1",
		step3Title: "intrebarea 2",
		step4Title: "intrebarea 3",
		step5Title: "Mulțumesc!",
		step1Paragraph: "Veți vedea fotografii nud. Vă rugăm să fiți discret.",
		step2Paragraph: "Multe dintre aceste femei sunt mame singure disperate și soții care înșală în căutarea unor distracții. Ar putea fi vecinii tăi sau cineva cunoscut. Sunteți de acord să păstrați secret identitatea acestor femei?",
		step3Paragraph: "Aceste femei ne-au cerut să nu permitem bărbaților care caută o „relație”. Nu doresc decât sex rapid. Nu se intalneste. Sunteți de acord cu această solicitare?",
		step4Paragraph: "Ai cel puțin 25 ani? Femeile au solicitat să nu îi lăsăm pe cei mai mici de 25 ani să îi contacteze din cauza comportamentului nepoliticos al bărbaților mai tineri.",
		step5Paragraph: "Acum puteți vedea lista noastră și fotografiile cu femeile din zona dvs. Din nou, vă rugăm să păstrați secretul identității lor. Faceți clic pe butonul „Continuați” și căutați pe baza răspunsurilor dvs.",
		btnContinue: "Continua",
		btnYes: "DA",
		btnNo: "NU",
		btnNext: "Următorul",
		btnBack: "Înapoi",
        adult: "doar pentru adulți",
        chatTitle: 'Activitate în zona ta',
        msgPhrase1: 'postează poza nud',
        msgPhrase2: 'face sex minunat',
        msgPhrase3: 'caută sex',
        msgPhrase4: 'te invit la petrecere nud',
	},
	zh: {
		step1Title: "警告！",
		step2Title: "问题 1",
		step3Title: "问题 2",
		step4Title: "问题 3",
		step5Title: "谢谢！",
		step1Paragraph: "您会看到裸照。请谨慎",
		step2Paragraph: "这些女性很多都是绝望的单身妈妈，或是为了找乐子而出轨的人妻。可能是您的邻居或您认识的人。您是否同意对她们的身份保密？",
		step3Paragraph: "这些女性要求过滤掉寻求“恋情”的男性。她们只需要快速性爱，而不是约会。您是否接受这种要求？",
		step4Paragraph: "您是否已满 25 岁？这些女性要求不要让 25 岁以下的未成年人联系她们，因为曾经遭受过年轻男性的粗鲁行为。",
		step5Paragraph: "您可以看到您所在区域的相关女性的名单和照片。再次强调，请对她们的身份保密。点击“继续”按钮，在您答案的基础上搜索。",
		btnContinue: "继续",
		btnYes: "是",
		btnNo: "否",
		btnNext: "下一个",
		btnBack: "上一个",
        adult: "仅限成人",
        chatTitle: '您所在地區的活動',
        msgPhrase1: '發布裸照',
        msgPhrase2: '做愛',
        msgPhrase3: '正在尋找性愛',
        msgPhrase4: '邀請你參加裸體派對',
	},
	pl: {
		step1Title: "OSTRZEŻENIE!",
		step2Title: "Pytanie 1",
		step3Title: "Pytanie 2",
		step4Title: "Pytanie 3",
		step5Title: "Dziękuję Ci!",
		step1Paragraph: "Zobaczysz nagie zdjęcia. Bądź dyskretny.",
		step2Paragraph: "Wiele z tych kobiet jest zrozpaczonymi samotnymi mamami i zdradzającymi żonami szukającymi dobrej zabawy. Mogą to być twoi sąsiedzi lub ktoś, kogo znasz. Czy zgadzasz się zachować tożsamość tych kobiet w tajemnicy?",
		step3Paragraph: "Te kobiety poprosiły nas, abyśmy nie zezwalali mężczyznom, którzy szukają „związku”. Chcą tylko szybkiego seksu. Nie umawiać się Czy zgadzasz się na tę prośbę?",
		step4Paragraph: "czy masz przynajmniej 25 lat? Kobiety poprosiły, aby nie pozwalać osobom młodszym niż 25 lat kontaktować się z nimi z powodu niegrzecznych zachowań młodszych mężczyzn.",
		step5Paragraph: "Możesz teraz zobaczyć naszą listę i zdjęcia kobiet z Twojej okolicy. Ponownie, proszę, zachowaj ich tożsamość w tajemnicy. Kliknij przycisk „Kontynuuj” i wyszukaj na podstawie swoich odpowiedzi.",
		btnContinue: "Kontyntynuj",
		btnYes: "TAK",
		btnNo: "NIE",
		btnNext: "Dalej",
		btnBack: "Wstecz",
        adult: "tylko dla dorosłych",
        chatTitle: 'Aktywność w Twojej okolicy',
        msgPhrase1: 'opublikować nagie zdjęcie',
        msgPhrase2: 'udanego seksu',
        msgPhrase3: 'szuka seksu',
        msgPhrase4: 'zapraszam na nagą imprezę',
	},
	it: {
		step1Title: "ATTENZIONE!",
		step2Title: "Domanda 1",
		step3Title: "Domanda 2",
		step4Title: "Domanda 3",
		step5Title: "Grazie!",
		step1Paragraph: "Potresti visualizzare foto di nudo. Ti preghiamo di essere discreto.",
		step2Paragraph: "Molte di queste donne sono mamme single disperate e mogli che tradiscono i loro mariti in cerca di divertimento. Potrebbero essere le tue vicine di casa o persone di tua conoscenza. Accetti di mantenere segreta l'identità di queste donne?",
		step3Paragraph: 'Queste donne ci hanno chiesto di non permettere agli uomini che cercano una "relazione seria" di contattarle. Vogliono solo sesso senza impegni. Nessun appuntamento serio. Accetti questa richiesta?',
		step4Paragraph: "Hai almeno 25 anni? Le donne ci hanno chiesto di non permettere a persone di età inferiore ai 25 anni di contattarle a causa del comportamento maleducato di alcuni giovani uomini in passato.",
		step5Paragraph: 'Adesso puoi visualizzare l\'elenco e le foto delle donne che si trovano nella tua zona. Ancora una volta, ti preghiamo di mantenere segreta la loro identità. Clicca sul pulsante "Continua" e cerca utenti in base alle tue risposte.',
		btnContinue: "Continua",
		btnYes: "SÌ",
		btnNo: "NO",
		btnNext: "Avanti",
		btnBack: "Indietro",
        adult: "Solo adulti",
        chatTitle: 'Attività nella tua zona',
        msgPhrase1: 'pubblica foto di nudo',
        msgPhrase2: 'fare un ottimo sesso',
        msgPhrase3: 'è in cerca di sesso',
        msgPhrase4: 'ti invitano a una festa nuda',
	},
	fr: {
		step1Title: "AVERTISSEMENT!",
		step2Title: "question 1",
		step3Title: "question 2",
		step4Title: "question 3",
		step5Title: "Merci !",
		step1Paragraph: "Vous verrez des photos nues. Soyez discret.",
		step2Paragraph: "Beaucoup de ces femmes sont des mères célibataires désespérées et des femmes infidèles à la recherche de plaisir. Elles pourraient être vos voisines ou quelqu'un que vous connaissez. Acceptez-vous de garder secrète l'identité de ces femmes ?",
		step3Paragraph: 'Ces femmes nous ont demandé de ne pas autoriser les hommes qui recherchent une "relation". Elles ne désirent que du sexe rapide. Ne pas sortir ensemble. Acceptez-vous cette demande ?',
		step4Paragraph: "Avez-vous au moins 25 ans ? Les femmes ont demandé que nous ne laissions pas les jeunes de moins de 25 ans les contacter en raison du comportement grossier des hommes plus jeunes.",
		step5Paragraph: 'Vous pouvez maintenant voir notre liste et des photos de femmes qui sont dans votre région. Encore une fois, veuillez garder leur identité secrète. Cliquez sur le bouton "Continuer" et effectuez une recherche sur la base de vos réponses.',
		btnContinue: "Continuer",
		btnYes: "OUI",
		btnNo: "NON",
		btnNext: "suivant",
		btnBack: "Retour",
        adult: "adulte seulement",
        chatTitle: 'Activité dans votre région',
        msgPhrase1: 'post photo nue',
        msgPhrase2: 'avoir un grand sexe',
        msgPhrase3: 'cherche du sexe',
        msgPhrase4: 'vous inviter à une soirée nue',
	},
	hr: {
		step1Title: "UPOZORENJE!",
		step2Title: "Pitanje 1",
		step3Title: "Pitanje 2",
		step4Title: "Pitanje 3",
		step5Title: "Hvala vam!",
		step1Paragraph: "Vidjet ćete gole fotografije. Molimo budite diskretni.",
		step2Paragraph: "Mnoge od tih žena očajne su samohrane mame i varaju supruge koje traže zabavu. Mogli bi vam biti susjedi ili netko koga poznajete. Slažete li se da identitet tih žena čuvate u tajnosti?",
		step3Paragraph: "Te žene su nas molile da ne dopustimo muškarcima koji traže \"vezu\". Žele samo brzi seks. Ne izlazi. Slažete li se sa ovim zahtjevom?",
		step4Paragraph: "Imate li barem 25 godina? Žene su zatražile da im ne dopustimo da kontaktiraju one mlađe od 25 godina zbog nepristojnog ponašanja mlađih muškaraca.",
		step5Paragraph: "Sada možete vidjeti naš popis i fotografije žena koje se nalaze u vašem kraju. Molim vas, čuvajte njihov identitet u tajnosti. Kliknite gumb \"Nastavi\" i pretražite na osnovu vaših odgovora.",
		btnContinue: "Nastaviti",
		btnYes: "DA",
		btnNo: "NE",
		btnNext: "Naprijed",
		btnBack: "Nazad",
        adult: "samo za odrasle",
        chatTitle: 'Aktivnost u vašem području',
        msgPhrase1: 'objava gole fotografije',
        msgPhrase2: 'imaju sjajan seks',
        msgPhrase3: 'traži seks',
        msgPhrase4: 'pozvati na gostu zabavu',
	},
	es: {
		step1Title: "¡ADVERTENCIA!",
		step2Title: "Pregunta 1",
		step3Title: "Pregunta 2",
		step4Title: "Pregunta 3",
		step5Title: "¡Gracias!",
		step1Paragraph: "Vas a ver fotos con desnudos. Por favor, sé discreto.",
		step2Paragraph: "Muchas de estas mujeres son madres solteras o casadas infieles que quieren pasarlo bien. Podrían ser tus vecinas o alguien a quien conoces. ¿Aceptas mantener en secreto la identidad de estas mujeres?",
		step3Paragraph: "Estas mujeres nos han pedido que no enseñemos sus perfiles a hombres que buscan una “relación”. Solo quieren sexo rápido. No quieren tener citas románticas. ¿Aceptas esta condición?",
		step4Paragraph: "¿Tienes al menos 25 años? Debido a malas experiencias relacionadas con el comportamiento de hombres jóvenes, las mujeres nos han pedido que no dejemos que contacten con ellas los menores de 25 años.",
		step5Paragraph: 'Ahora puedes ver nuestra lista de mujeres de tu zona y sus fotos. Te pedimos una vez más que mantengas su identidad en secreto. Haz clic en el botón “Continuar" y efectúa una búsqueda conforme a tus respuestas.',
		btnContinue: "Continuar",
		btnYes: "SÍ",
		btnNo: "NO",
		btnNext: "Siguiente",
		btnBack: "Anterior",
        adult: "Solo adultos",
        chatTitle: 'Actividad en tu área',
        msgPhrase1: 'publicar foto desnuda',
        msgPhrase2: 'tener un buen sexo',
        msgPhrase3: 'está buscando sexo',
        msgPhrase4: 'invitarte a una fiesta desnuda',
	},
	hu: {
		step1Title: "FIGYELEM!",
		step2Title: "1. kérdés",
		step3Title: "2. kérdés",
		step4Title: "3. kérdés",
		step5Title: "Köszönöm!",
		step1Paragraph: "Látni fogja a meztelen fényképeket. Kérjük, legyen óvatos.",
		step2Paragraph: "Ezek közül a nők közül sokan kétségbeesett egyedülálló anyukák és csaló feleségek, akik szórakozást keresnek. Lehet, hogy a szomszédok vagy valaki, akit ismersz. Egyetért-e azzal, hogy titokban tartja e nők identitását?",
		step3Paragraph: "Ezek a nők arra kérték bennünket, hogy ne engedjük be a férfiakat, akik „kapcsolatot” keresnek. Csak a gyors szexre vágynak. Nem randevú. Ön elfogadja ezt a kérést?",
		step4Paragraph: "Legalább 25 éves vagy? A nők azt kérték, hogy ne engedjük, hogy a 25 éven aluli gyermekek kapcsolatba lépjenek velük a fiatalabb férfiak korábbi durva viselkedése miatt.",
		step5Paragraph: 'Most láthatja a környékünkön lévő nők listáját és fényképeit. Ismét kérjük, tartsa titokban titkát. Kattintson a "Folytatás" gombra, és válaszok alapján keressen.',
		btnContinue: "Folytatni",
		btnYes: "IGEN",
		btnNo: "NEM",
		btnNext: "következő",
		btnBack: "Vissza",
        adult: "csak felnőtt",
        chatTitle: 'Tevékenység a környéken',
        msgPhrase1: 'post meztelen fénykép',
        msgPhrase2: 'nagyszerű szex',
        msgPhrase3: 'szexet keres',
        msgPhrase4: 'meghívlak meztelen partira',
	},
	pt: {
		step1Title: "ATENÇÃO!",
		step2Title: "questão 1",
		step3Title: "questão 2",
		step4Title: "questão 3",
		step5Title: "obrigado!",
		step1Paragraph: "Vais ver fotos com nudez. Por favor sê discreto.",
		step2Paragraph: "Muitas destas mulheres são mães desesperadas e cornudas que procuram alguma diversão. Podem até ser tuas vizinhas ou alguém que conheces. Comprometes-te a manter a identidade destas mulheres secreta?",
		step3Paragraph: "Estas mulheres pediram-nos para não aceitar homens que procuram uma \"relação\". Elas apenas querem uma queca rápida. Não querem namoro. Concordas?",
		step4Paragraph: "És maior de idade? Estas mulheres pediram para que não permitissemos que homens com menos de 25 anos as contactassem, pois já houve casos de comportamento rude por parte de menores.",
		step5Paragraph: "Já podes ver a nossa lista e fotos de mulheres na tua zona. Novamente, por favor mantém a sua identidade secreta. Clica em \"Continuar\" e pesquisa com base nas tuas respostas.",
		btnContinue: "Continuar",
		btnYes: "SIM",
		btnNo: "NÃO",
		btnNext: "Seguinte",
		btnBack: "Anterior",
        adult: "para adultos apenas",
        chatTitle: 'Atividade em sua área',
        msgPhrase1: 'postar foto nua',
        msgPhrase2: 'tenha um ótimo sexo',
        msgPhrase3: 'está procurando sexo',
        msgPhrase4: 'convidamos você para uma festa de nudez',
	},
	vi: {
		step1Title: "CẢNH BÁO!",
		step2Title: "câu hỏi 1",
		step3Title: "câu hỏi 2",
		step4Title: "câu hỏi 3",
		step5Title: "Cảm ơn bạn!",
		step1Paragraph: "Bạn sẽ thấy ảnh khỏa thân. Xin hãy cẩn thận.",
		step2Paragraph: "Nhiều người trong số những người phụ nữ này đang tuyệt vọng làm mẹ đơn thân và những người vợ lừa dối để tìm kiếm niềm vui. Họ có thể là hàng xóm của bạn hoặc người mà bạn biết. Bạn có đồng ý giữ bí mật danh tính của những người phụ nữ này không?",
		step3Paragraph: "Những người phụ nữ này đã yêu cầu chúng tôi không cho phép những người đàn ông đang tìm kiếm một \"mối quan hệ\". Họ chỉ ham muốn tình dục nhanh chóng. Không hẹn hò. Bạn có đồng ý với yêu cầu này không?",
		step4Paragraph: "Bạn ít nhất 25 tuổi? Những người phụ nữ đã yêu cầu chúng tôi không để những người dưới 25 tuổi liên lạc với họ vì những hành vi thô lỗ trong quá khứ của những người đàn ông trẻ hơn.",
		step5Paragraph: "Bây giờ bạn có thể xem danh sách của chúng tôi và hình ảnh của những người phụ nữ trong khu vực của bạn. Một lần nữa, xin vui lòng giữ bí mật danh tính của họ. Nhấp vào nút \"Tiếp tục\" và tìm kiếm trên cơ sở câu trả lời của bạn.",
		btnContinue: "Tiếp tục",
		btnYes: "CÓ",
		btnNo: "KHÔNG",
		btnNext: "Tiếp theo",
		btnBack: "Quay lại",
        adult: "chỉ người lớn",
        chatTitle: 'Hoạt động trong khu vực của bạn',
        msgPhrase1: 'đăng ảnh khỏa thân',
        msgPhrase2: 'có một tình dục tuyệt vời',
        msgPhrase3: 'đang tìm kiếm tình dục',
        msgPhrase4: 'mời bạn trong bữa tiệc khỏa thân',
	},
	cs: {
		step1Title: "VAROVÁNÍ!",
		step2Title: "Otázka 1",
		step3Title: "Otázka 2",
		step4Title: "Otázka 3",
		step5Title: "Děkuji!",
		step1Paragraph: "Uvidíte nahé fotografie. Buďte diskrétní.",
		step2Paragraph: "Mnoho z těchto žen jsou zoufalé svobodné maminky a podvádějící manželky hledající nějakou zábavu. Mohli by to být vaši sousedé nebo někdo, koho znáte. Souhlasíte, že budete udržovat identitu těchto žen v tajnosti?",
		step3Paragraph: "Tyto ženy nás požádaly, abychom nedovolili mužům, kteří hledají „vztah“. Chtějí jen rychlý sex. Ne randění. Souhlasíte s touto žádostí?",
		step4Paragraph: "Máte nejméně 25 let? Ženy požádaly, abychom nedovolili těm mladším 25 let, aby je kontaktovali kvůli minulému hrubému chování mladších mužů.",
		step5Paragraph: "Nyní můžete vidět náš seznam a fotografie žen, které jsou ve vaší oblasti. Znovu udržujte jejich identitu v tajnosti. Klikněte na tlačítko \"Pokračovat\" a hledejte na základě vašich odpovědí.",
		btnContinue: "Pokračovat",
		btnYes: "ANO",
		btnNo: "ŽÁDNÉ",
		btnNext: "další",
		btnBack: "Zpět",
        adult: "pouze pro dospělé",
        chatTitle: 'Aktivita ve vaší oblasti',
        msgPhrase1: 'zveřejnit nahou fotku',
        msgPhrase2: 'mít skvělý sex',
        msgPhrase3: 'hledá sex',
        msgPhrase4: 'pozvat vás na nahé párty',
	},
	sr: {
		step1Title: "УПОЗОРЕЊЕ!",
		step2Title: "Питање 1",
		step3Title: "Питање 2",
		step4Title: "Питање 3",
		step5Title: "Хвала вам!",
		step1Paragraph: "Видећете голе фотографије. Молимо будите дискретни.",
		step2Paragraph: "Многе од ових жена су очајне самохране маме и варају супруге које траже забаву. Они могу бити ваши сусједи или неко кога познајете. Да ли се слажете да идентитет тих жена чувате у тајности?",
		step3Paragraph: "Те жене су нас замолиле да не дозволимо мушкарцима који траже „везу“. Желе само брзи секс. Не излази. Да ли се слажете са овим захтевом?",
		step4Paragraph: "Да ли имате најмање 25 година? Жене су затражиле да им не дозволимо да контактирају оне млађе од 25 година због непристојног понашања млађих мушкараца.",
		step5Paragraph: "Сада можете видети нашу листу и фотографије жена које се налазе у вашем крају. Молим вас, чувајте њихов идентитет у тајности. Кликните на дугме \"Настави\" и претражите на основу ваших одговора.",
		btnContinue: "Настави",
		btnYes: "ДА",
		btnNo: "НЕ",
		btnNext: "на следеће",
		btnBack: "Натраг",
        adult: "само за одрасле",
        chatTitle: 'Активност у вашем крају',
        msgPhrase1: 'објави голишаву фотографију',
        msgPhrase2: 'имају сјајан секс',
        msgPhrase3: 'тражи секс',
        msgPhrase4: 'позвати на голу забаву',
	},
	el: {
		step1Title: "ΠΡΟΕΙΔΟΠΟΙΗΣΗ!",
		step2Title: "Ερώτηση 1",
		step3Title: "Ερώτηση 2",
		step4Title: "Ερώτηση 3",
		step5Title: "Σας ευχαριστώ!",
		step1Paragraph: "Θα δείτε γυμνές φωτογραφίες. Να είστε διακριτικοί.",
		step2Paragraph: "Πολλές από αυτές τις γυναίκες είναι απεγνωσμένες μονομαχίες και εξαπατώντας τις γυναίκες αναζητώντας κάποια διασκέδαση. Θα μπορούσαν να είναι οι γείτονές σας ή κάποιος που γνωρίζετε. Συμφωνείτε να κρατήσετε μυστική την ταυτότητα αυτών των γυναικών;",
		step3Paragraph: "Αυτές οι γυναίκες μας ζήτησαν να μην επιτρέψουμε στους άνδρες που αναζητούν μια \"σχέση\". Απλώς επιθυμούν γρήγορο σεξ. Δεν χρονολογείται. Συμφωνείτε με αυτό το αίτημα;",
		step4Paragraph: "Είστε τουλάχιστον 25 ετών; Οι γυναίκες ζήτησαν να μην τους αφήσουμε να έρθουν σε επαφή με όσους είναι κάτω των 25 ετών λόγω προηγούμενης αγενής συμπεριφοράς των νεότερων ανδρών.",
		step5Paragraph: "Τώρα μπορείτε να δείτε τη λίστα και τις φωτογραφίες των γυναικών που βρίσκονται στην περιοχή σας. Και πάλι, παρακαλώ κρατήστε την ταυτότητά τους μυστική. Κάντε κλικ στο κουμπί \"Συνέχεια\" και αναζητήστε με βάση τις απαντήσεις σας.",
		btnContinue: "Να συνεχίσει",
		btnYes: "ΝΑΙ",
		btnNo: "ΟΧΙ",
		btnNext: "Επόμενο",
		btnBack: "Επιστροφή",
        adult: "μόνο για ενήλικες",
        chatTitle: 'Δραστηριότητα στην περιοχή σας',
        msgPhrase1: 'μετά γυμνή φωτογραφία',
        msgPhrase2: 'έχω υπέροχο σεξ',
        msgPhrase3: 'ψάχνει για σεξ',
        msgPhrase4: 'σας προσκαλούν σε γυμνό πάρτι',
	},
	th: {
		step1Title: "คำเตือน!",
		step2Title: "คำถามที่ 1",
		step3Title: "คำถามที่ 2",
		step4Title: "คำถามที่ 3",
		step5Title: "ขอขอบคุณ!",
		step1Paragraph: "คุณจะเห็นภาพเปลือย โปรดระมัดระวัง",
		step2Paragraph: "ผู้หญิงเหล่านี้หลายคนหมดหวังกับคุณแม่โสดและภรรยานอกใจที่กำลังมองหาความสนุกสนาน พวกเขาอาจเป็นเพื่อนบ้านของคุณหรือคนที่คุณรู้จัก คุณเห็นด้วยที่จะรักษาความลับของผู้หญิงเหล่านี้หรือไม่?",
		step3Paragraph: "ผู้หญิงเหล่านี้ขอให้เราไม่อนุญาตให้ผู้ชายที่กำลังมองหา \"ความสัมพันธ์\" พวกเขาต้องการเพียงเพศที่รวดเร็ว ไม่ออกเดท คุณเห็นด้วยกับคำขอนี้หรือไม่?",
		step4Paragraph: "คุณอายุอย่างน้อย 25 ปี? ผู้หญิงขอให้เราไม่อนุญาตให้เด็กอายุน้อยกว่า 25 ปีติดต่อพวกเขาเพราะพฤติกรรมที่หยาบคายในอดีตโดยชายหนุ่ม",
		step5Paragraph: "ตอนนี้คุณสามารถดูรายการและรูปภาพของผู้หญิงที่อยู่ในพื้นที่ของคุณ อีกครั้งโปรดเก็บข้อมูลเป็นความลับ คลิกที่ปุ่ม \"ดำเนินการต่อ\" และค้นหาตามคำตอบของคุณ",
		btnContinue: "ต่อ",
		btnYes: "ใช่",
		btnNo: "ไม่ใช่",
		btnNext: "ถัดไป",
		btnBack: "ย้อนกลับ",
        adult: "ผู้ใหญ่เท่านั้น",
        chatTitle: 'กิจกรรมในพื้นที่ของคุณ',
        msgPhrase1: 'โพสต์ภาพเปลือย',
        msgPhrase2: 'มีเพศสัมพันธ์ที่ดี',
        msgPhrase3: 'กำลังมองหาเพศ',
        msgPhrase4: 'เชิญคุณเข้าร่วมปาร์ตี้นู้ด',
	},
	de: {
		step1Title: "WARNUNG!",
		step2Title: "Frage 1",
		step3Title: "Frage 2",
		step4Title: "Frage 3",
		step5Title: "Vielen Dank!",
		step1Paragraph: "Sie werden Nacktfotos sehen. Bitte seien Sie diskret.",
		step2Paragraph: "Viele dieser Frauen sind verzweifelte alleinerziehende Mütter und verheiratete Frauen, die auf der Suche nach etwas Spaß sind. Es könnte Ihre Nachbarin oder jemand sein, den Sie kennen. Sind Sie damit einverstanden, die Identität dieser Frauen geheim zu halten?",
		step3Paragraph: "Diese Frauen haben uns gebeten, keine Männer zuzulassen, die auf der Suche nach einer \"Beziehung\" sind. Sie wünschen nur schnellen Sex. Keine Verabredungen. Stimmen Sie dieser Bitte zu?",
		step4Paragraph: "Sind Sie mindestens 25 Jahre alt? Die Frauen haben darum gebeten, dass wir nicht zulassen, dass sich Personen unter 25 Jahren wegen unhöflichen Verhaltens jüngerer Männer mit ihnen in Verbindung setzen.",
		step5Paragraph: "Sie können jetzt auf unsere Liste und Fotos von Frauen zugreifen, die in Ihrer Nähe sind. Bitte halten Sie ihre Identität geheim. Klicken Sie auf die Schaltfläche \"Weiter\" und starten Sie die Suche anhand Ihrer Antworten.",
		btnContinue: "Weiter",
		btnYes: "JA",
		btnNo: "NEIN",
		btnNext: "Weiter",
		btnBack: "Zurück",
        adult: "Nur für Erwachsene",
        chatTitle: 'Aktivität in Ihrer Nähe',
        msgPhrase1: 'Post Nacktfoto',
        msgPhrase2: 'habe einen tollen Sex',
        msgPhrase3: 'sucht Sex',
        msgPhrase4: 'lade dich auf eine nackte Party ein',
	},
	da: {
		step1Title: "Advarsel!",
		step2Title: "spørgsmål 1",
		step3Title: "spørgsmål 2",
		step4Title: "spørgsmål 3",
		step5Title: "Tak!",
		step1Paragraph: "Du vil se nøgne billeder. Vær diskret.",
		step2Paragraph: "Mange af disse kvinder er desperate enlige mødre og utro hustruer, som er på udkig efter noget sjov. De kan være dine naboer eller nogen, du kender. Er du enig i at holde disse kvinders identitet hemmelig?",
		step3Paragraph: "Disse kvinder har bedt os om ikke at tillade mænd, der leder efter et \"forhold\". De ønsker kun hurtig sex. Ikke dating. Er du enig i denne anmodning?",
		step4Paragraph: "Er du mindst 25 år? Kvinderne har anmodet om, at vi ikke lader personer, som er yngre end 25, kontakte dem på grund af tidligere uhøflig opførsel fra yngre mænd.",
		step5Paragraph: "Du kan nu se vores liste og billeder af kvinder, som er i dit område. Hold venligst deres identitet hemmelig. Klik på knappen \"Fortsæt\" og søg på baggrund af dine svar.",
		btnContinue: "Fortsæt",
		btnYes: "JA",
		btnNo: "NEJ",
		btnNext: "Næste",
		btnBack: "Tilbage",
        adult: "kun for voksne",
        chatTitle: 'Aktivitet i dit område',
        msgPhrase1: 'post nøgenfoto',
        msgPhrase2: 'have en dejlig sex',
        msgPhrase3: 'leder efter sex',
        msgPhrase4: 'inviterer dig til nøgen fest',
	},
	nl: {
		step1Title: "Waarschuwing!",
		step2Title: "Vraag 1",
		step3Title: "Vraag 2",
		step4Title: "Vraag 3",
		step5Title: "dank je!",
		step1Paragraph: "Je zal naaktfoto's zien. Graag discreet zijn.",
		step2Paragraph: "Veel van deze vrouwen zijn wanhopige alleenstaande moeders en vreemdgaande vrouwen die op zoek zijn naar plezier. Ze zouden je buren kunnen zijn, of iemand die je kent. Ga je akkoord met het geheimhouden van de identiteit van deze vrouwen?",
		step3Paragraph: "Deze vrouwen hebben ons gevraagd geen mannen toe te staan ​​die een 'relatie' zoeken. Ze verlangen alleen naar snelle seks. Geen dating. Gaat u akkoord met dit verzoek?",
		step4Paragraph: "Ben je minstens 25 jaar oud? De vrouwen hebben gevraagd om mannen onder de 25 jaar te vermijden vanwege onbeleefd gedrag van jongere mannen.",
		step5Paragraph: "Mogelijk zie je nu onze lijst en foto's van vrouwen in uw omgeving. Nogmaals, houd hun identiteit geheim. Klik op de knop \"Doorgaan\" en zoek op basis van jouw antwoorden.",
		btnContinue: "Doorgaan",
		btnYes: "JA",
		btnNo: "NEE",
		btnNext: "Volgende",
		btnBack: "Terug",
        adult: "Alleen volwassenen",
        chatTitle: 'Activiteit in uw omgeving',
        msgPhrase1: 'post naaktfoto',
        msgPhrase2: 'heb een geweldige seks',
        msgPhrase3: 'is op zoek naar seks',
        msgPhrase4: 'nodigen u uit op naaktfeest',
	},
	sv: {
		step1Title: "VARNING!",
		step2Title: "fråga 1",
		step3Title: "fråga 2",
		step4Title: "fråga 3",
		step5Title: "tack!",
		step1Paragraph: "Du kommer att se nakenbilder. Respektera användarnas integritet",
		step2Paragraph: "Många av dessa kvinnor är ofta desperata och ensamma mammor men det förekommerm även fruar som bedrar sina män eller vill endast ha lite kul utanför sitt nuvarande äktenskap. De kan vara dina grannar eller någon du känner. Håller du med att hålla kvinnornas identitet hemlig?",
		step3Paragraph: "Dessa kvinnor har bett oss att inte bli kopplade ihop med män som söker en seriös relation . De önskar endast komma i kontakt med män som vill ha snabb sex. Inga dejter. Håller du med den här begäran?",
		step4Paragraph: "Är du minst 25 år gammal? Kvinnorna har begärt att vi inte låter de yngre än 25 åt kontakta dessa på grund av tidigare obefogade beteenden från yngre män.",
		step5Paragraph: "Du kan nu beakta vår lista och foton på kvinnor inom ditt närområde. Återigen, säkerställ att du respekterar deras integritet och håller deras identitet hemligt. Klicka på \"Fortsätt\" och sök på grundval.",
		btnContinue: "Fortsätta",
		btnYes: "JA",
		btnNo: "NEJ",
		btnNext: "nästa",
		btnBack: "Tillbaka",
        adult: "endast vuxen",
        chatTitle: 'Aktivitet i ditt område',
        msgPhrase1: 'post nakenfoto',
        msgPhrase2: 'ha ett bra sex',
        msgPhrase3: 'letar efter sex',
        msgPhrase4: 'bjuder in dig på nakenparty',
	},
	ja: {
		step1Title: "警告！",
		step2Title: "質問 1",
		step3Title: "質問 2",
		step4Title: "質問 3",
		step5Title: "ありがとうございます！",
		step1Paragraph: "ヌード写真が含まれます。ご注意ください。",
		step2Paragraph: "これらの女性の多くは、刺激を求めているシングルマザーや人妻です。これらの女性は、あなたの近所の住人または知人かもしれません。これらの女性の身元情報を秘密にすることに同意しますか？",
		step3Paragraph: "これらの女性は、「交際関係」を求めている男性を求めていません。これらの女性は、セックスだけの関係を求めています。デート相手を探しているわけではありません。あなたはこのリクエストに同意できますか？",
		step4Paragraph: "あなたは少なくとも25歳ですか？これらの女性は、過去に若い男性から失礼な態度を取られたため、25歳未満の男性とのコンタクトを求めていません。",
		step5Paragraph: "あなたの地域にいる女性のリストと写真を見ることができます。女性の身元情報に関しては、秘密にしてください。「続行」ボタンをクリックして、あなたの回答に基づいて検索します。",
		btnContinue: "続行",
		btnYes: "はい",
		btnNo: "いいえ",
		btnNext: "次へ",
		btnBack: "戻る",
        adult: "成人のみ",
        chatTitle: 'お住まいの地域での活動',
        msgPhrase1: 'ヌード写真を投稿する',
        msgPhrase2: '素晴らしいセックスをする',
        msgPhrase3: 'セックスを探しています',
        msgPhrase4: 'ヌードパーティーにあなたを招待',
	},
	fa: {
		step1Title: "هشدار!",
		step2Title: "1 سوال",
		step3Title: "2 سوال",
		step4Title: "3 سوال",
		step5Title: "متشکرم!",
		step1Paragraph: "عکس های برهنه را مشاهده خواهید کرد. لطفا باهوش باشید.",
		step2Paragraph: "بسیاری از این زنان مادران مجرد هستند و همسران تقلب به دنبال سرگرمی هستند. آنها می توانند همسایگان شما یا شخصی باشند که می شناسید. آیا قبول دارید که هویت این زنان راز مخفی نگه دارید؟",
		step3Paragraph: "این زنان از ما خواسته اند كه اجازه ندهیم مردانی كه به دنبال \"رابطه\" هستند. آنها فقط خواهان رابطه جنسی سریع هستند. قرار ملاقات نیست آیا با این درخواست موافق هستید؟",
		step4Paragraph: "ایا شما حداقل 25 سال دارید؟ زنان درخواست کرده اند که ما به دلیل رفتار ناشایست گذشته مردان جوان ، اجازه ندهیم افراد جوانتر از 25 سال با آنها ارتباط برقرار کنند.",
		step5Paragraph: "اکنون می توانید لیست و عکسهای ما از زنانی که در منطقه شما هستند را ببینید. باز هم ، لطفا هویت آنها را مخفی نگه دارید. بر روی دکمه \"ادامه\" کلیک کرده و بر اساس پاسخ های خود جستجو کنید.",
		btnContinue: "ادامه هید",
		btnYes: "بله",
		btnNo: "خیر",
		btnNext: "بازگشت",
		btnBack: "بعدی",
        adult: "فقط بزرگسالان",
        chatTitle: 'فعالیت در منطقه شما',
        msgPhrase1: 'عکس برهنه ارسال کنید',
        msgPhrase2: 'رابطه جنسی خوبی داشته باشید',
        msgPhrase3: 'به دنبال رابطه جنسی است',
        msgPhrase4: 'شما را در مهمانی برهنه دعوت کنید',
	},
	id: {
		step1Title: "PERINGATAN!",
		step2Title: "pertanyaan 1",
		step3Title: "pertanyaan 2",
		step4Title: "pertanyaan 3",
		step5Title: "Terima kasih!",
		step1Paragraph: "Anda akan melihat foto-foto telanjang. Harap berhati-hati.",
		step2Paragraph: "Banyak dari wanita ini adalah ibu tunggal yang putus asa dan istri selingkuh yang mencari kesenangan. Mereka bisa jadi tetangga Anda atau seseorang yang Anda kenal. Apakah Anda setuju untuk merahasiakan identitas wanita-wanita ini?",
		step3Paragraph: "Para wanita ini meminta kami untuk tidak mengizinkan pria yang mencari \"hubungan\". Mereka hanya menginginkan seks cepat. Tidak berkencan. Apakah Anda menyetujui permintaan ini?",
		step4Paragraph: "Apakah Anda setidaknya berumur 25 tahun? Para wanita telah meminta agar kami tidak membiarkan mereka yang berusia di bawah 25 tahun menghubungi mereka karena perilaku kasar masa lalu oleh pria yang lebih muda.",
		step5Paragraph: "Anda sekarang dapat melihat daftar dan foto-foto wanita yang ada di daerah Anda. Sekali lagi, tolong jaga kerahasiaan identitas mereka. Klik tombol \"Lanjutkan\" dan cari berdasarkan jawaban Anda.",
		btnContinue: "Terus",
		btnYes: "IYA",
		btnNo: "TIDAK",
		btnNext: "Berikutnya",
		btnBack: "Kembali",
        adult: "dewasa saja",
        chatTitle: 'Aktivitas di daerah Anda',
        msgPhrase1: 'memposting foto telanjang',
        msgPhrase2: 'berhubungan seks yang hebat',
        msgPhrase3: 'sedang mencari seks',
        msgPhrase4: 'mengundang Anda di pesta telanjang',
	},
};

$(document).ready(function() {
	var langBrowser = navigator.language || (navigator.languages && navigator.languages[0]),
		param = langs[langBrowser];
	if(param == undefined && langBrowser && langBrowser.length > 0) {
		var parsedLang = langBrowser.slice(0, 2);
		if(langs[parsedLang]) {
			param = langs[parsedLang];
		}
	}
	if(param == undefined) {
		param = langs["en"];
		// 'en' - default language, if you want change language, please select in object abbreviation. Example: 'fr', 'ru' etc.
		$(".step-1 .step__header h1").text(param.step1Title);
		$(".step-1 .step__body p").text(param.step1Paragraph);
		$(".step-2 .step__header h6").text(param.step2Title);
		$(".step-2 .step__body p").text(param.step2Paragraph);
		$(".step-3 .step__header h6").text(param.step3Title);
		$(".step-3 .step__body p").text(param.step3Paragraph);
		$(".step-4 .step__header h6").text(param.step4Title);
		$(".step-4 .step__body p").text(param.step4Paragraph);
		$(".step-5 .step__header h2").text(param.step5Title);
		$(".step-5 .step__body p").text(param.step5Paragraph);
		$(".btn-continue").text(param.btnContinue);
		$('.btn-back').text(param.btnBack);
		$('.btn-next').text(param.btnNext);
		$(".btn-yes").text(param.btnYes);
        $(".btn-no").text(param.btnNo);
        
        $('.sweetchat h6').text(param.chatTitle);
        $('.msg-phrase-1').text(param.msgPhrase1);
        $('.msg-phrase-2').text(param.msgPhrase2);
        $('.msg-phrase-3').text(param.msgPhrase3);
        $('.msg-phrase-4').text(param.msgPhrase4);
	} else {
		$(".step-1 .step__header h1").text(param.step1Title);
		$(".step-1 .step__body p").text(param.step1Paragraph);
		$(".step-2 .step__header h6").text(param.step2Title);
		$(".step-2 .step__body p").text(param.step2Paragraph);
		$(".step-3 .step__header h6").text(param.step3Title);
		$(".step-3 .step__body p").text(param.step3Paragraph);
		$(".step-4 .step__header h6").text(param.step4Title);
		$(".step-4 .step__body p").text(param.step4Paragraph);
		$(".step-5 .step__header h2").text(param.step5Title);
		$(".step-5 .step__body p").text(param.step5Paragraph);
		$(".btn-continue").text(param.btnContinue);
		$('.btn-back').text(param.btnBack);
		$('.btn-next').text(param.btnNext);
		$(".btn-yes").text(param.btnYes);
        $(".btn-no").text(param.btnNo);
        
        $('.sweetchat h6').text(param.chatTitle);
        $('.msg-phrase-1').text(param.msgPhrase1);
        $('.msg-phrase-2').text(param.msgPhrase2);
        $('.msg-phrase-3').text(param.msgPhrase3);
        $('.msg-phrase-4').text(param.msgPhrase4);
	}
});